// GENERATED by scripts/import-lucide.ts from the legacy zzon-doc renderer — do not edit.
import type { IconRef } from "../icons/aliases.ts";

export interface CategoryMeta {
  labelKo: string;
  icon: IconRef;
  colorGroup: keyof typeof CATEGORY_COLORS_LIGHT;
}

export const CATEGORY_META = {
  "user": {
    "labelKo": "사용자",
    "icon": "x.lucide-user",
    "colorGroup": "user"
  },
  "frontend": {
    "labelKo": "프론트엔드",
    "icon": "x.lucide-monitor",
    "colorGroup": "frontend"
  },
  "mobile": {
    "labelKo": "모바일",
    "icon": "x.lucide-smartphone",
    "colorGroup": "frontend"
  },
  "backend": {
    "labelKo": "백엔드",
    "icon": "x.lucide-server",
    "colorGroup": "backend"
  },
  "service": {
    "labelKo": "서비스",
    "icon": "x.lucide-boxes",
    "colorGroup": "backend"
  },
  "worker": {
    "labelKo": "워커",
    "icon": "x.lucide-cog",
    "colorGroup": "backend"
  },
  "lambda": {
    "labelKo": "람다",
    "icon": "x.lucide-zap",
    "colorGroup": "compute"
  },
  "scheduler": {
    "labelKo": "스케줄러",
    "icon": "x.lucide-clock",
    "colorGroup": "compute"
  },
  "db": {
    "labelKo": "데이터베이스",
    "icon": "x.lucide-database",
    "colorGroup": "data"
  },
  "table": {
    "labelKo": "테이블",
    "icon": "x.lucide-table2",
    "colorGroup": "data"
  },
  "cache": {
    "labelKo": "캐시",
    "icon": "x.lucide-memory-stick",
    "colorGroup": "data-aux"
  },
  "queue": {
    "labelKo": "큐",
    "icon": "x.lucide-list-ordered",
    "colorGroup": "data-aux"
  },
  "storage": {
    "labelKo": "스토리지",
    "icon": "x.lucide-hard-drive",
    "colorGroup": "data-aux"
  },
  "cdn": {
    "labelKo": "CDN",
    "icon": "x.lucide-globe",
    "colorGroup": "edge"
  },
  "gateway": {
    "labelKo": "게이트웨이",
    "icon": "x.lucide-door-open",
    "colorGroup": "edge"
  },
  "auth": {
    "labelKo": "인증",
    "icon": "x.lucide-shield-check",
    "colorGroup": "edge"
  },
  "agent": {
    "labelKo": "에이전트",
    "icon": "x.lucide-bot",
    "colorGroup": "claude"
  },
  "skill": {
    "labelKo": "스킬",
    "icon": "x.lucide-wand2",
    "colorGroup": "claude"
  },
  "hook": {
    "labelKo": "훅",
    "icon": "x.lucide-webhook",
    "colorGroup": "claude"
  },
  "doc": {
    "labelKo": "문서",
    "icon": "x.lucide-file-text",
    "colorGroup": "neutral"
  },
  "other": {
    "labelKo": "기타",
    "icon": "x.lucide-box",
    "colorGroup": "neutral"
  },
  "lb": {
    "labelKo": "로드밸런서",
    "icon": "x.lucide-shuffle",
    "colorGroup": "edge"
  },
  "dns": {
    "labelKo": "DNS",
    "icon": "x.lucide-globe",
    "colorGroup": "edge"
  },
  "firewall": {
    "labelKo": "방화벽",
    "icon": "x.lucide-brick-wall",
    "colorGroup": "edge"
  },
  "monitor": {
    "labelKo": "관측",
    "icon": "x.lucide-activity",
    "colorGroup": "neutral"
  },
  "secret": {
    "labelKo": "시크릿",
    "icon": "x.lucide-key-round",
    "colorGroup": "edge"
  },
  "ml": {
    "labelKo": "ML/AI",
    "icon": "x.lucide-sparkles",
    "colorGroup": "compute"
  },
  "analytics": {
    "labelKo": "분석",
    "icon": "x.lucide-chart-column",
    "colorGroup": "data"
  },
  "topic": {
    "labelKo": "토픽",
    "icon": "x.lucide-rss",
    "colorGroup": "data-aux"
  },
  "pipeline": {
    "labelKo": "파이프라인",
    "icon": "x.lucide-workflow",
    "colorGroup": "compute"
  },
  "device": {
    "labelKo": "디바이스",
    "icon": "x.lucide-cpu",
    "colorGroup": "frontend"
  }
} as unknown as Record<string, CategoryMeta>;

export const CATEGORY_COLORS_LIGHT = {
  "user": "#64748b",
  "frontend": "#0ea5e9",
  "backend": "#8b5cf6",
  "compute": "#f59e0b",
  "data": "#10b981",
  "data-aux": "#14b8a6",
  "edge": "#f43f5e",
  "external": "#71717a",
  "claude": "#a855f7",
  "neutral": "#6b7280"
} as const;
export const CATEGORY_COLORS_DARK = {
  "user": "#94a3b8",
  "frontend": "#38bdf8",
  "backend": "#a78bfa",
  "compute": "#fbbf24",
  "data": "#34d399",
  "data-aux": "#2dd4bf",
  "edge": "#fb7185",
  "external": "#a1a1aa",
  "claude": "#c084fc",
  "neutral": "#9ca3af"
} as const;

export type CategoryName = keyof typeof CATEGORY_META;
