/**
 * One-shot import of the legacy zzon-doc renderer's visual vocabulary:
 * 52 lucide stroke icons + 31 node categories + 10 color groups.
 *
 * Reads ../skills/zzon-doc/scripts/render.mjs, writes:
 *   src/icons/svg/x.lucide-<name>.svg   (wrapped stroke SVGs)
 *   src/icons/manifest.gen.ts           (appends missing x.lucide-* keys)
 *   src/render/categories.gen.ts        (CATEGORY_META + light/dark palettes)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const RENDER = join(ROOT, "..", "skills", "zzon-doc", "scripts", "render.mjs");
const src = readFileSync(RENDER, "utf8");

// ---- ICONS map ----
const iconsBlock = src.match(/const ICONS = \{([\s\S]*?)\n\};/)?.[1];
if (!iconsBlock) throw new Error("ICONS map not found in render.mjs");
const icons = new Map<string, string>();
for (const m of iconsBlock.matchAll(/^\s{2}(\w+): '([\s\S]*?)',?$/gm)) {
  icons.set(m[1]!, m[2]!);
}
console.log(`parsed ${icons.size} lucide icons`);

const lucideKey = (name: string) =>
  `x.lucide-${name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase()}`;

for (const [name, inner] of icons) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${inner}</svg>`;
  writeFileSync(join(ROOT, "src", "icons", "svg", `${lucideKey(name).replace(/^x\./, "x.")}.svg`), svg);
}

// ---- manifest append (idempotent) ----
const manifestPath = join(ROOT, "src", "icons", "manifest.gen.ts");
let manifest = readFileSync(manifestPath, "utf8");
const missing = [...icons.keys()]
  .map((n) => lucideKey(n))
  .filter((k) => !manifest.includes(`"${k}"`));
if (missing.length) {
  const lines = missing
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(`src/icons/svg/${k}.svg`)},`)
    .join("\n");
  manifest = manifest.replace("} as const;", `${lines}\n} as const;`);
  writeFileSync(manifestPath, manifest);
}
console.log(`manifest: +${missing.length} lucide keys`);

// ---- CATEGORY_META ----
const catBlock = src.match(/const CATEGORY_META = \{([\s\S]*?)\n\s*\};/)?.[1];
if (!catBlock) throw new Error("CATEGORY_META not found");
const cats: Record<string, { labelKo: string; icon: string; colorGroup: string }> = {};
for (const m of catBlock.matchAll(/(\w+):\{labelKo:"([^"]+)",icon:"(\w+)",colorGroup:"([\w-]+)"\}/g)) {
  cats[m[1]!] = { labelKo: m[2]!, icon: lucideKey(m[3]!), colorGroup: m[4]! };
}
console.log(`parsed ${Object.keys(cats).length} categories`);

// ---- palettes (--cat-* vars, light + dark) ----
const grabPalette = (block: string) => {
  const out: Record<string, string> = {};
  for (const m of block.matchAll(/--cat-([\w-]+):(#[0-9a-fA-F]{6})/g)) out[m[1]!] = m[2]!;
  return out;
};
const rootBlock = src.match(/:root \{([\s\S]*?)\}/)?.[1] ?? "";
const darkBlock = src.match(/\.dark \{([\s\S]*?)\}/)?.[1] ?? "";
const light = grabPalette(rootBlock);
const dark = grabPalette(darkBlock);
console.log(`palettes: light ${Object.keys(light).length} / dark ${Object.keys(dark).length} groups`);

const body = `// GENERATED by scripts/import-lucide.ts from the legacy zzon-doc renderer — do not edit.
import type { IconRef } from "../icons/aliases.ts";

export interface CategoryMeta {
  labelKo: string;
  icon: IconRef;
  colorGroup: keyof typeof CATEGORY_COLORS_LIGHT;
}

export const CATEGORY_META = ${JSON.stringify(cats, null, 2)} as unknown as Record<string, CategoryMeta>;

export const CATEGORY_COLORS_LIGHT = ${JSON.stringify(light, null, 2)} as const;
export const CATEGORY_COLORS_DARK = ${JSON.stringify(dark, null, 2)} as const;

export type CategoryName = keyof typeof CATEGORY_META;
`;
writeFileSync(join(ROOT, "src", "render", "categories.gen.ts"), body);
console.log("wrote src/render/categories.gen.ts");
